<?php

namespace app\index\controller;

use app\index\model\User;
use think\Cache;
use think\captcha\Captcha;
use think\Controller;
use think\Hook;
use think\Request;
use think\Session;

class Enroll extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        Hook::listen('my_axios');

    }

    /**
     * 生成验证码
     *
     * @return \think\Response
     */
    public function index()
    {
//        ob_clean();
//        $config = config('captcha');
//        $sid=request()->get('sid');
        $number = time().mt_rand(1000,9999);
        session_id($number);
        Session::init([
            'auto_start' => true
        ]);
        $config = [
            'imageH' => 50,
            'imageW' => 150,
            'fontSize' => 18,
            'expire' => 300
        ];
        $captcha  = new Captcha($config);
        return $captcha->entry($number);
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
//        $verifycode = Cache::pull('verifycode');
//        return json([
//            'code' => $verifycode
//        ]);
        $number = time().mt_rand(1000,9999);
        session_id($number);
        Session::init([
            'auto_start' => true
        ]);
        $captcha = new Captcha();
        $res= $captcha->check(input('post.img'),$number);#seession标识

        $validate = validate('Enroll');
        if (!$validate->batch()->check(request()->param())) {
            if (!$res) {
                return json([
                    'status' => 401,
                    'msg' => $validate->getError(),
//                'data' => Session::get('ThinkPHP.CN', '')
                ]);
            }

        }

        $user = new User();
        $user->user_name = input('post.user_name');
        $user->user_password = md5(input('post.user_password'));
        $user->user_email = input('post.user_email');
        $user->user_phone = input('post.user_phone');
        $user->enroll_time = date('Y-m-d H:i:s', time());
        $result = $user->save();
        if ($result) {
            return json([
                'status' => 200,
                'msg' => '注册成功'
            ]);
        } else {
            return json([
                'status' => 402,
                'msg' => '注册失败'
            ]);
        }

    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
