<?php
namespace app\admin\controller;

use think\Controller;
use think\Hook;

class Index extends Controller
{
//    public function _initialize()
//    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
//        Hook::listen('login');
//    }

    public function index()
    {
//        Hook::listen('login');
        return view();
    }

    public function login()
    {
        return view();
    }
}
